(defconst m 1000000007)

(defun make-spans ()
  (let ((spans nil)
        (i 0))
    (while (< i 80)
      (let ((start (* i 13)))
        (push (vector start (+ start 5 (% i 7)) (% i 5)) spans))
      (setq i (1+ i)))
    spans))

(defun adjust-pos (x pos del ins)
  (let* ((del-end (+ pos del))
         (after-del (cond ((<= x pos) x)
                          ((>= x del-end) (- x del))
                          (t pos))))
    (if (>= after-del pos) (+ after-del ins) after-del)))

(defun adjust-span (span pos del ins)
  (vector (adjust-pos (aref span 0) pos del ins)
          (adjust-pos (aref span 1) pos del ins)
          (aref span 2)))

(defun adjust-spans (spans pos del ins)
  (let ((out nil))
    (dolist (span spans)
      (push (adjust-span span pos del ins) out))
    (nreverse out)))

(defun score-spans (spans)
  (let ((acc 0))
    (dolist (span spans)
      (setq acc (% (+ acc (* (aref span 0) 3) (* (aref span 1) 5) (* (aref span 2) 7)) m)))
    acc))

(let ((spans (make-spans))
      (doclen 5000)
      (i 0))
  (while (< i 2500)
    (let* ((pos (% (+ (* i 97) (/ doclen 3)) doclen))
           (want-del (if (= (% i 4) 0) 3 1))
           (del (min want-del (- doclen pos)))
           (ins (cond ((= (% i 5) 0) 0)
                      ((= (% i 5) 1) 1)
                      ((= (% i 5) 2) 4)
                      ((= (% i 5) 3) 2)
                      (t 0))))
      (setq spans (adjust-spans spans pos del ins))
      (setq doclen (max 1 (+ (- doclen del) ins))))
    (setq i (1+ i)))
  (princ (format "%d\n" (% (+ (score-spans spans) (* doclen 11)) m))))
