(defconst m 1000000007)

(defun checksum-string (s)
  (let ((i 0)
        (acc 0))
    (while (< i (length s))
      (setq acc (% (+ (* acc 33) (aref s i)) m))
      (setq i (1+ i)))
    acc))

(defun make-state ()
  (vector "" 0 '("goto gamma" "open beta" "grep alpha") -1 "" "" 'edit "" -1 "" 0))

(defun st-buffer (st) (aref st 0))
(defun st-cursor (st) (aref st 1))
(defun st-history (st) (aref st 2))
(defun st-hpos (st) (aref st 3))
(defun st-saved (st) (aref st 4))
(defun st-kill (st) (aref st 5))
(defun st-mode (st) (aref st 6))
(defun st-search (st) (aref st 7))
(defun st-search-idx (st) (aref st 8))
(defun st-saved-buffer (st) (aref st 9))
(defun st-saved-cursor (st) (aref st 10))

(defun st-set (st i v) (aset st i v) st)

(defun insert-text (st text)
  (let* ((b (st-buffer st))
         (p (st-cursor st)))
    (st-set st 0 (concat (substring b 0 p) text (substring b p)))
    (st-set st 1 (+ p (length text)))))

(defun line-start (b p)
  (while (and (> p 0) (/= (aref b (1- p)) 10))
    (setq p (1- p)))
  p)

(defun line-stop (b p)
  (while (and (< p (length b)) (/= (aref b p) 10))
    (setq p (1+ p)))
  p)

(defun word-byte-p (ch)
  (or (and (>= ch ?0) (<= ch ?9))
      (and (>= ch ?A) (<= ch ?Z))
      (and (>= ch ?a) (<= ch ?z))
      (>= ch 128)))

(defun space-byte-p (ch)
  (or (= ch 32) (= ch 9) (= ch 10)))

(defun skip-back (b p pred)
  (while (and (> p 0) (funcall pred (aref b (1- p))))
    (setq p (1- p)))
  p)

(defun key-left (st)
  (st-set st 1 (max 0 (1- (st-cursor st)))))

(defun key-right (st)
  (st-set st 1 (min (length (st-buffer st)) (1+ (st-cursor st)))))

(defun delete-range (st a z)
  (let ((b (st-buffer st)))
    (st-set st 0 (concat (substring b 0 a) (substring b z)))
    (st-set st 1 a)))

(defun kill-range (st a z)
  (let ((b (st-buffer st)))
    (delete-range st a z)
    (st-set st 5 (substring b a z))))

(defun key-kill-line-end (st)
  (let* ((b (st-buffer st))
         (p (st-cursor st))
         (e (line-stop b p)))
    (if (and (= p e) (< p (length b)))
        (kill-range st p (1+ p))
      (kill-range st p e))))

(defun key-kill-word (st)
  (let* ((b (st-buffer st))
         (p (st-cursor st))
         (a (skip-back b (skip-back b p #'space-byte-p)
                       (lambda (ch) (not (space-byte-p ch))))))
    (kill-range st a p)))

(defun nth-entry (xs n)
  (or (nth n xs) ""))

(defun search-scan (history query from)
  (let ((rest (nthcdr from history))
        (i from)
        (found nil))
    (while (and rest (not found))
      (when (string-match-p (regexp-quote query) (car rest))
        (setq found (cons i (car rest))))
      (setq rest (cdr rest))
      (setq i (1+ i)))
    found))

(defun search-apply (st from)
  (let ((q (st-search st)))
    (unless (string= q "")
      (let ((hit (search-scan (st-history st) q from)))
        (when hit
          (st-set st 8 (car hit))
          (st-set st 0 (cdr hit))
          (st-set st 1 (length (cdr hit)))))))
  st)

(defun search-step (st key)
  (cond
   ((consp key)
    (st-set st 7 (concat (st-search st) (cdr key)))
    (search-apply st (max 0 (st-search-idx st))))
   ((eq key 'c-r)
    (search-apply st (1+ (st-search-idx st))))
   ((eq key 'c-c)
    (st-set st 6 'edit)
    (st-set st 0 (st-saved-buffer st))
    (st-set st 1 (st-saved-cursor st)))
   (t
    (st-set st 6 'edit))))

(defun step (st key)
  (if (eq (st-mode st) 'search)
      (search-step st key)
    (cond
     ((consp key) (insert-text st (cdr key)))
     ((eq key 'left) (key-left st))
     ((eq key 'right) (key-right st))
     ((eq key 'c-a) (st-set st 1 (line-start (st-buffer st) (st-cursor st))))
     ((eq key 'c-e) (st-set st 1 (line-stop (st-buffer st) (st-cursor st))))
     ((eq key 'c-k) (key-kill-line-end st))
     ((eq key 'c-u) (kill-range st (line-start (st-buffer st) (st-cursor st)) (st-cursor st)))
     ((eq key 'c-w) (key-kill-word st))
     ((eq key 'c-y) (unless (string= (st-kill st) "") (insert-text st (st-kill st))) st)
     ((eq key 'up)
      (let* ((p (st-hpos st))
             (n (1+ p)))
        (when (< n (length (st-history st)))
          (when (= p -1) (st-set st 4 (st-buffer st)))
          (st-set st 3 n)
          (st-set st 0 (nth-entry (st-history st) n))
          (st-set st 1 (length (st-buffer st)))))
      st)
     ((eq key 'down)
      (let ((p (st-hpos st)))
        (cond ((= p -1) st)
              ((= p 0)
               (st-set st 3 -1)
               (st-set st 0 (st-saved st))
               (st-set st 1 (length (st-buffer st))))
              (t
               (st-set st 3 (1- p))
               (st-set st 0 (nth-entry (st-history st) (1- p)))
               (st-set st 1 (length (st-buffer st))))))
      st)
     ((eq key 'delete)
      (let ((p (st-cursor st)))
        (when (< p (length (st-buffer st)))
          (delete-range st p (1+ p))))
      st)
     ((eq key 'c-r)
      (st-set st 6 'search)
      (st-set st 7 "")
      (st-set st 8 -1)
      (st-set st 9 (st-buffer st))
      (st-set st 10 (st-cursor st)))
     (t st))))

(defun key-for (j)
  (cond ((= j 0) (cons 'char "a"))
        ((= j 1) (cons 'char "b"))
        ((= j 2) (cons 'char "c"))
        ((= j 3) 'left)
        ((= j 4) (cons 'char "X"))
        ((= j 5) 'right)
        ((= j 6) 'c-a)
        ((= j 7) 'c-k)
        ((= j 8) 'c-y)
        ((= j 9) 'c-e)
        ((= j 10) 'c-w)
        ((= j 11) 'c-y)
        ((= j 12) 'c-r)
        ((= j 13) (cons 'char "g"))
        ((= j 14) 'c-r)
        ((= j 15) 'c-c)
        ((= j 16) 'up)
        ((= j 17) 'down)
        ((= j 18) 'tab)
        ((= j 19) 'delete)
        (t 'c-u)))

(defun state-score (st)
  (% (+ (+ (checksum-string (st-buffer st)) (checksum-string (st-kill st)))
        (+ (+ (checksum-string (st-saved st)) (checksum-string (st-search st)))
           (+ (checksum-string (car (st-history st)))
              (+ (st-cursor st) (* (1+ (st-hpos st)) 17)))))
     m))

(defun reset-state (st)
  (st-set st 0 "")
  (st-set st 1 0)
  (st-set st 6 'edit)
  (st-set st 3 -1))

(let ((st (make-state))
      (acc 0)
      (i 0))
  (while (< i 2500)
    (let ((j 0))
      (while (< j 21)
        (setq st (step st (key-for j)))
        (setq j (1+ j))))
    (setq acc (% (+ acc (state-score st)) m))
    (setq st (reset-state st))
    (setq i (1+ i)))
  (princ (format "%d\n" acc)))
