(defconst m 1000000007)

(defun checksum (s n)
  (let ((i 0)
        (acc 0))
    (while (< i n)
      (setq acc (% (+ (* acc 131) (aref s i)) m))
      (setq i (1+ i)))
    acc))

(defun line-text (i)
  (format "line %d :: alpha beta gamma %d" i (% i 17)))

(defun render-line (row width acc)
  (let* ((text (line-text row))
         (n (min width (length text))))
    (% (+ (* acc 17) (checksum text n)) m)))

(defun render-range (row stop width acc)
  (while (< row stop)
    (setq acc (render-line row width acc))
    (setq row (1+ row)))
  acc)

(defun render-state (state acc)
  (let* ((top (aref state 0))
         (height (aref state 2))
         (width (aref state 3))
         (split (aref state 4))
         (first-stop (+ top (if (> split 0) split height)))
         (acc1 (render-range top first-stop width acc)))
    (if (> split 0)
        (render-range (+ top split) (+ top height) width acc1)
      acc1)))

(defun update-state (i state)
  (let ((top (aref state 0))
        (point (aref state 1))
        (height (aref state 2))
        (width (aref state 3))
        (split (aref state 4)))
    (cond
     ((= (% i 10) 0) (vector top (min 999 (1+ point)) height width split))
     ((= (% i 10) 1) (vector top (max 0 (1- point)) height width split))
     ((= (% i 10) 2) (vector (min 960 (1+ top)) point height width split))
     ((= (% i 10) 3) (vector (max 0 (1- top)) point height width split))
     ((= (% i 10) 4) (vector top point height (+ 40 (% i 50)) split))
     ((= (% i 10) 5) (vector top point (+ 12 (% i 15)) width split))
     ((= (% i 10) 6) (vector top point height width (if (= split 0) (/ height 2) 0)))
     ((= (% i 10) 7) (vector point point height width split))
     ((= (% i 10) 8) (vector top (% (* i 37) 1000) height width split))
     (t state))))

(let ((state (vector 0 0 24 80 0))
      (acc 0)
      (i 0))
  (while (< i 4000)
    (setq state (update-state i state))
    (setq acc (render-state state acc))
    (setq i (1+ i)))
  (princ (format "%d\n" acc)))
