(defconst m 1000000007)

(defun st-get (st i) (aref st i))
(defun st-set (st i v) (aset st i v) st)

(defun cmd-left (st)
  (st-set st 0 (max 0 (1- (st-get st 0)))))

(defun cmd-right (st)
  (st-set st 0 (min (st-get st 1) (1+ (st-get st 0)))))

(defun cmd-home (st)
  (st-set st 0 0))

(defun cmd-end (st)
  (st-set st 0 (st-get st 1)))

(defun cmd-insert (st)
  (st-set st 1 (+ (st-get st 1) 1))
  (st-set st 0 (+ (st-get st 0) 1))
  (st-set st 3 (+ (st-get st 3) 1)))

(defun cmd-insert-fast (st)
  (st-set st 1 (+ (st-get st 1) 2))
  (st-set st 0 (+ (st-get st 0) 2))
  (st-set st 3 (+ (st-get st 3) 1)))

(defun cmd-delete (st)
  (when (< (st-get st 0) (st-get st 1))
    (st-set st 1 (1- (st-get st 1)))
    (st-set st 3 (1+ (st-get st 3))))
  st)

(defun cmd-mark (st)
  (st-set st 2 (+ (st-get st 2) (st-get st 0))))

(defun cmd-recenter (st)
  (st-set st 3 (+ (st-get st 3) (% (st-get st 0) 7))))

(defun cmd-indent (st)
  (st-set st 0 (min (st-get st 1) (+ (st-get st 0) 2)))
  (st-set st 3 (1+ (st-get st 3))))

(let ((base (make-sparse-keymap))
      (mode (make-sparse-keymap))
      (minor (make-sparse-keymap)))
  (define-key base [left] #'cmd-left)
  (define-key base [right] #'cmd-right)
  (define-key base [insert] #'cmd-insert)
  (define-key base [delete] #'cmd-delete)
  (define-key base [mark] #'cmd-mark)
  (define-key mode [c-a] #'cmd-home)
  (define-key mode [c-e] #'cmd-end)
  (define-key mode [tab] #'cmd-indent)
  (define-key minor [insert] #'cmd-insert-fast)
  (define-key minor [c-l] #'cmd-recenter)
  (defconst editor-keymaps (list minor mode base)))

(defun key-for (i)
  (let ((r (% i 16)))
    (cond ((= r 0) 'insert)
          ((= r 1) 'right)
          ((= r 2) 'insert)
          ((= r 3) 'left)
          ((= r 4) 'mark)
          ((= r 5) 'c-e)
          ((= r 6) 'delete)
          ((= r 7) 'c-a)
          ((= r 8) 'insert)
          ((= r 9) 'c-l)
          ((= r 10) 'right)
          ((= r 11) 'tab)
          ((= r 12) 'delete)
          ((= r 13) 'mark)
          ((= r 14) 'left)
          (t 'insert))))

(defun lookup-in-maps (key)
  (catch 'found
    (let ((seq (vector key)))
      (dolist (map editor-keymaps)
        (let ((handler (lookup-key map seq)))
          (when (functionp handler)
            (throw 'found handler)))))
    nil))

(let ((st (vector 0 0 0 0))
      (i 0))
  (while (< i 120000)
    (let ((handler (lookup-in-maps (key-for i))))
      (when handler
        (setq st (funcall handler st))))
    (setq i (1+ i)))
  (princ (format "%d\n"
                 (% (+ (+ (st-get st 0) (* (st-get st 1) 3))
                       (+ (% (st-get st 2) m) (* (st-get st 3) 11)))
                    m))))
