(defconst m 1000000007)

(defun checksum-string (s)
  (let ((i 0)
        (acc 0)
        (n (length s)))
    (while (< i n)
      (setq acc (% (+ (* acc 33) (aref s i)) m))
      (setq i (1+ i)))
    acc))

(defun op-pos (i len)
  (% (+ (* i 37) (/ i 7)) (1+ len)))

(with-temp-buffer
  (dotimes (i 160)
    (insert (format "line %d alpha beta gamma\n" i)))
  (let ((p 0)
        (i 0))
    (while (< i 2500)
      (let* ((n (buffer-size))
             (op (% i 8)))
        (cond
         ((= op 0)
          (goto-char (1+ p))
          (insert "x")
          (setq p (1+ p)))
         ((= op 1)
          (goto-char (1+ p))
          (insert "\n")
          (setq p (1+ p)))
         ((= op 2)
          (setq p (op-pos i n)))
         ((= op 3)
          (when (< p n)
            (delete-region (1+ p) (1+ (min n (1+ p)))))
          (setq p (min p (buffer-size))))
         ((= op 4)
          (goto-char (1+ p))
          (insert "()")
          (setq p (+ p 2)))
         ((= op 5)
          (setq p (max 0 (- p (+ 1 (% i 5))))))
         ((= op 6)
          (when (< p n)
            (delete-region (1+ p) (1+ (min n (+ p 3)))))
          (setq p (min p (buffer-size))))
         (t
          (setq p (min n (+ p (+ 1 (% i 7))))))))
      (setq i (1+ i)))
    (let ((text (buffer-substring-no-properties (point-min) (point-max))))
      (princ (format "%d\n" (% (+ (checksum-string text) (+ (* (length text) 17) p)) m))))))
