(defconst m 1000000007)
(defconst rx-comment "#[^\n]*")
(defconst rx-string "\"[^\"]*\"")
(defconst rx-number "[0-9]+")
(defconst rx-word "[A-Za-z_][A-Za-z0-9_]*")

(defun sample-text ()
  (let ((i 0)
        (acc ""))
    (while (< i 120)
      (setq acc (concat acc (format "def name_%d = \"value%d\" # comment %d\n" i i i)))
      (setq i (1+ i)))
    acc))

(defun choose (best rx text pos kind)
  (if (not (string-match rx text pos))
      best
    (let ((s (match-beginning 0))
          (e (match-end 0)))
      (if (or (null best) (< s (aref best 0)))
          (vector s e kind)
        best))))

(defun scan-one (text pos)
  (let ((best nil))
    (setq best (choose best rx-comment text pos 1))
    (setq best (choose best rx-string text pos 2))
    (setq best (choose best rx-number text pos 3))
    (setq best (choose best rx-word text pos 4))
    best))

(defun scan-loop (text)
  (let ((pos 0)
        (acc 0)
        (n (length text)))
    (while (< pos n)
      (let ((hit (scan-one text pos)))
        (if (not hit)
            (setq pos n)
          (let ((s (aref hit 0))
                (e (aref hit 1))
                (kind (aref hit 2)))
            (setq acc (% (+ acc (* s 3) (* e 5) (* kind 7)) m))
            (setq pos (if (> e s) e (1+ s)))))))
    acc))

(let ((text (sample-text))
      (i 0)
      (acc 0))
  (while (< i 25)
    (setq acc (% (+ acc (scan-loop text)) m))
    (setq i (1+ i)))
  (princ (format "%d\n" acc)))
