(let ((xs nil)
      (i 0)
      (acc 0))
  (while (< i 100000)
    (setq xs (cons i xs))
    (setq i (1+ i)))
  (while xs
    (setq acc (% (+ acc (car xs)) 1000000007))
    (setq xs (cdr xs)))
  (princ (format "%d\n" acc)))
