(let ((rx "\\([[:alpha:]]+\\|_+\\)[0-9]\\{2,3\\}")
      (s "xxab123--__99--zz7")
      (acc 0)
      (i 0))
  (while (< i 200000)
    (when (string-match-p rx s)
      (setq acc (1+ acc)))
    (setq i (1+ i)))
  (princ (format "%d\n" acc)))
