(let ((rx "\\([[:alpha:]]+\\|_+\\)[0-9]\\{2,3\\}")
      (s "xxab123--__99--zz7")
      (acc 0)
      (i 0))
  (while (< i 200000)
    (string-match rx s)
    (setq acc (+ acc (- (match-end 0) (match-beginning 0))))
    (setq i (1+ i)))
  (princ (format "%d\n" acc)))
