#ifndef IDM_EXPAND_INTERNAL_H
#define IDM_EXPAND_INTERNAL_H

#include "idiom/actor.h"
#include "idiom/expand.h"
#include "idiom/artifact.h"
#include "idiom/prims.h"
#include "idiom/vm.h"
#include <dirent.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#define IDM_FRAME_ENV 0u
#define IDM_FRAME_TOP 1u

typedef struct {
    char *name;
    IdmScopeSet scopes;
    IdmCaptureKind kind;
    uint32_t source_index;
    uint32_t capture_index;
    IdmBindingId binding_id;
    IdmArity arity;
    bool slot_synthetic;
    bool has_contract;
    IdmCallableContract contract;
} CaptureBinding;
typedef struct {
    size_t table_base;
    uint32_t next_slot;
    uint32_t arg_slots;
    size_t bits_binder_base;
    size_t clause_table_base;
} SavedClauseContext;
typedef struct {
    const char *name;
    const IdmSyntax *name_syntax;
    IdmScopeSet scopes;
    uint32_t slot;
    IdmArity arity;
    size_t *indices;
    size_t count;
    size_t cap;
    bool exported;
    bool has_contract;
    IdmCallableContract contract;
    char *doc;
} DefnGroup;
typedef struct {
    const char **names;
    IdmSpan *spans;
    bool *matched;
    size_t count;
} UseSelection;
typedef struct ExpandContext ExpandContext;
typedef IdmCore *(*NativeSurfaceFn)(struct ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, IdmError *err);
typedef struct {
    IdmModuleRef *module;
    uint32_t function_index;
    IdmPhaseEnv *phase_env;
    NativeSurfaceFn native;
} PhaseSyntaxFn;
typedef struct {
    char *name;
    PhaseSyntaxFn fn;
    bool exported;
    bool hidden;
} MacroDef;
typedef struct {
    char *name;
    IdmScopeSet scopes;
    PhaseSyntaxFn fn;
} CoreFormDef;
typedef struct {
    char *name;
    IdmScopeSet scopes;
    IdmEnforestNode *node;
    bool transformer;
    PhaseSyntaxFn fn;
} ReaderFormDef;
typedef struct {
    IdmEnforestNode *node;
    bool transformer;
    PhaseSyntaxFn fn;
} ReaderFormBinding;
typedef struct {
    IdmSyntax **outer;
    char **fresh;
    size_t *clause;
    size_t count;
    size_t cap;
} PinCollect;
typedef struct SavedFunctionContext_s {
    size_t table_base;
    uint32_t frame;
    uint32_t next_slot;
    uint32_t arg_slots;
    CaptureBinding *captures;
    size_t capture_count;
    size_t capture_cap;
    struct SavedFunctionContext_s *prev;
    const IdmCallableContract *function_contract;
    PinCollect *pin_collect;
} SavedFunctionContext;
typedef struct {
    IdmSymbol *trait;
    IdmSymbol *trait_key;
    IdmSymbol *name;
    char *provider;
    char *provider_key;
    IdmArity arity;
    bool has_dispatch;
    bool dispatch_env;
    uint32_t dispatch_frame;
    uint32_t dispatch_slot;
    char *dispatch_env_key;
    IdmScopeSet scopes;
} MethodSurfaceDef;
typedef struct {
    IdmSymbol *name;
    IdmArity arity;
    bool has_contract;
    IdmCallableContract contract;
    bool has_default;
    bool seen_decl;
    IdmCore *default_fn;
    IdmScopeSet scopes;
    bool exported;
    uint32_t dispatch_slot;
    bool has_dispatch;
    uint32_t default_slot;
    bool has_default_slot;
} TraitMethodDef;
typedef struct {
    char *name;
    IdmSymbol *identity;
    bool exported;
    IdmArtifact *art;
} ProtocolDef;
typedef struct {
    IdmSymbol *name;
    bool exported;
    IdmTraitRequirementDef *requirements;
    size_t requirement_count;
    TraitMethodDef *methods;
    size_t method_count;
    bool dispatch_env;
    char *dispatch_env_key;
} TraitDef;
typedef struct {
    uint32_t method_surface;
    IdmSymbol *trait;
    IdmSymbol *name;
    IdmSymbol *type;
    IdmArity arity;
    bool impl_env;
    uint32_t impl_frame;
    char *impl_env_key;
    uint32_t impl_slot;
    bool has_contract;
    IdmCallableContract contract;
} MethodImplDef;
typedef struct {
    IdmSymbol *name;
    bool has_contract;
    IdmTypeTerm contract;
} TypeFieldDef;
typedef struct {
    IdmTypeTerm term;
} TypeMemberDef;
typedef struct {
    char *name;
    IdmSymbol *identity;
    bool exported;
    IdmScopeSet scopes;
    TypeMemberDef *members;
    size_t member_count;
    TypeFieldDef *fields;
    size_t field_count;
} TypeDef;
typedef struct {
    IdmTypedEntityKind kind;
    union {
        ProtocolDef protocol;
        TraitDef trait;
        TypeDef type;
    } as;
} TypedEntity;
typedef struct {
    TypedEntity *entities;
    size_t entity_count;
    size_t entity_cap;
    MethodSurfaceDef *method_surfaces;
    size_t method_surface_count;
    size_t method_surface_cap;
    MethodImplDef *method_impls;
    size_t method_impl_count;
    size_t method_impl_cap;
} TypedRegistry;
typedef struct {
    size_t entity_count;
    size_t method_surface_count;
    size_t method_impl_count;
} TypedRegistryCheckpoint;
typedef struct {
    IdmPkgGrammar artifact;
    IdmScopeSet binding_scopes;
    char *provider;
    char *provider_key;
} GrammarDef;
typedef struct {
    char *name;
    char *provider;
    char *provider_key;
    IdmBindingSpace space;
    int phase;
    IdmScopeSet scopes;
} SurfaceInstall;

typedef struct {
    const char *kind;
    char *name;
    char *provider;
    int phase;
    bool value_context;
    bool command_sub;
    IdmSpan span;
    char *before;
    char *after;
    char *doc;
} ExpandEdge;
typedef struct {
    char *name;
    IdmScopeSet scopes;
    IdmSyntax **items;
    size_t count;
    size_t run_id;
    uint32_t slot;
    IdmArity arity;
    bool has_contract;
    IdmCallableContract contract;
    bool in_progress;
    bool done;
} PhaseCandidate;
typedef struct {
    void *local_expand_user;
    IdmLocalExpandFn local_expand;
    void *free_identifier_eq_user;
    IdmFreeIdentifierEqFn free_identifier_eq;
    void *identifier_bound_user;
    IdmIdentifierBoundFn identifier_bound;
} SavedHooks;
typedef struct {
    const void *art;
    unsigned char hash[32];
    IdmScopeId base;
    size_t init_emit_mark[2];
    size_t runtime_init_mark[2];
} ArtifactRuntimeState;
typedef struct {
    IdmScopeId next_scope;
    uint32_t env_slot_seq;
    uint32_t next_slot;
    size_t binding_count;
    size_t macro_count;
    size_t grammar_count;
    size_t decl_grammar_count;
    size_t operator_count;
    TypedRegistryCheckpoint typed;
    size_t decl_method_count;
    size_t decl_core_form_count;
    size_t decl_reader_forms_count;
    size_t activation_count;
    size_t surface_install_count;
    size_t artifact_base_count;
    size_t init_emit_mark_count;
    size_t runtime_init_mark_count;
    size_t phase_runtime_init_mark_count;
    size_t package_slot_ref_count;
    size_t package_slot_count;
    size_t field_selector_count;
    size_t phase_candidate_count;
    uint64_t reader_generation;
} SurfaceCheckpoint;
typedef struct {
    char *env_key;
    uint32_t slot;
} PackageSlotRef;
typedef struct {
    char *name;
    uint32_t slot;
    bool env;
    bool emitted;
    char *env_key;
} FieldSelectorDef;
typedef struct {
    const IdmCore *core;
    IdmTypeTerm term;
} SolvedNodeType;
typedef struct ExpandContext {
    IdmRuntime *rt;
    IdmBindingTable bindings;
    IdmScopeSet empty_scopes;
    uint32_t next_slot;
    uint32_t arg_slots;
    CaptureBinding *captures;
    size_t capture_count;
    size_t capture_cap;
    uint32_t frame;
    uint32_t frame_seq;
    uint32_t env_slot_seq;
    bool in_package;
    const char *package_name;
    IdmPkgSlot *package_slots;
    size_t package_slot_count;
    size_t package_slot_cap;
    MacroDef *macros;
    size_t macro_count;
    size_t macro_cap;
    GrammarDef *grammars;
    size_t grammar_count;
    size_t grammar_cap;
    IdmOperatorDef *operators;
    size_t operator_count;
    size_t operator_cap;
    TypedRegistry typed;
    TraitMethodDef *decl_methods;
    size_t decl_method_count;
    size_t decl_method_cap;
    IdmMacroRunner *runner;
    IdmMacroRunner local_runner;
    IdmScopeStore scope_store;
    uint32_t surface_depth;
    int phase;
    int surface_phase;
    bool value_context;
    bool command_sub_context;
    bool suppress_method_impl_surface_refresh;
    struct BodyDefCtx *def_ctx;
    const IdmScopeSet *op_fallback;
    bool repl_env_binds;
    FieldSelectorDef *field_selectors;
    size_t field_selector_count;
    size_t field_selector_cap;
    struct { char *name; char *provider; char *provider_key; IdmSpan span; } *activations;
    size_t activation_count;
    size_t activation_cap;
    SurfaceInstall *surface_installs;
    size_t surface_install_count;
    size_t surface_install_cap;
    ExpandEdge *edges;
    size_t edge_count;
    size_t edge_cap;
    bool record_edges;
    CoreFormDef *decl_core_form;
    size_t decl_core_form_count;
    size_t decl_core_form_cap;
    ReaderFormDef *decl_reader_forms;
    size_t decl_reader_forms_count;
    size_t decl_reader_forms_cap;
    IdmPkgGrammar *decl_grammars;
    size_t decl_grammar_count;
    size_t decl_grammar_cap;
    IdmReaderArtifact *active_reader;
    uint64_t reader_generation;
    const char *unit_source;
    const char *unit_label;
    uint64_t unit_reader_generation;
    bool unit_read_incomplete;
    IdmScopeId unit_package_scope;
    bool kernel_mode;
    PhaseCandidate *phase_candidates;
    size_t phase_candidate_count;
    size_t phase_candidate_cap;
    size_t phase_candidate_run_seq;
    char *phase_demand_diag;
    SavedFunctionContext *enclosing;
    IdmPhaseEnv *phase_env;
    const char *trait_name;
    const char *trait_key;
    bool kernel_wrap;
    bool kernel_phase_seeded;
    ArtifactRuntimeState *artifact_bases;
    size_t artifact_base_count;
    size_t artifact_base_cap;
    size_t init_emit_mark_count;
    size_t runtime_init_mark_count;
    size_t phase_runtime_init_mark_count;
    PackageSlotRef *package_slot_refs;
    size_t package_slot_ref_count;
    size_t package_slot_ref_cap;
    IdmArtifactDep *deps;
    size_t dep_count;
    size_t dep_cap;
    const char *unit;
    char unit_key[17];
    const char *primitive_home;
    const IdmSyntax **pat_binders;
    size_t pat_binder_count;
    size_t pat_binder_cap;
    bool pat_binder_collect;
    uint32_t body_depth;
    uint32_t type_var_seq;
    const IdmCallableContract *function_contract;
    char **bits_binder_names;
    uint32_t *bits_binder_slots;
    size_t bits_binder_count;
    size_t bits_binder_cap;
    size_t clause_table_base;
    IdmSyntax **match_size_outer;
    char **match_size_fresh;
    uint32_t *match_size_slots;
    size_t *match_size_clause;
    size_t match_size_count;
    size_t match_size_cap;
    size_t match_size_depth;
    size_t match_size_clause_index;
    uint32_t bits_size_seq;
    PinCollect *pin_collect;
    uint32_t pin_value_seq;
    uint32_t pin_key_seq;
    SolvedNodeType *solved_nodes;
    size_t solved_node_count;
    size_t solved_node_cap;
} ExpandContext;
typedef struct BodyDefCtx {
    struct BodyDefCtx *prev;
} BodyDefCtx;
typedef struct {
    ExpandContext *ctx;
    IdmSyntax *const *items;
    size_t end;
    size_t pos;
    IdmError *err;
} EnforestParser;
typedef struct {
    IdmSymbol *name;
    IdmArity arity;
    IdmCore *fn;
    bool has_contract;
    IdmCallableContract contract;
} TraitMethodImpl;
typedef struct {
    char *path;
    IdmArtifact art;
} CachedPackage;
typedef struct {
    char *path;
    unsigned char hash[32];
} CachedPackageAction;
typedef struct {
    IdmRuntime *rt;
    IdmArtifact kernel;
    char *kernel_path;
    IdmScopeId kernel_scope_end;
    bool kernel_ready;
    IdmPhaseEnv *kernel_seed_phase_env;
    IdmReaderArtifact *source_reader;
    char *source_reader_path;
    unsigned char source_reader_hash[32];
    bool source_reader_hash_ready;
    CachedPackage **pkgs;
    size_t pkg_count;
    size_t pkg_cap;
    IdmArtifact **interned;
    size_t interned_count;
    size_t interned_cap;
    const char **compiling;
    size_t compiling_count;
    size_t compiling_cap;
    CachedPackageAction *actions;
    size_t action_count;
    size_t action_cap;
} ExpandCache;
ExpandCache *expand_cache_get(IdmRuntime *rt);
const IdmArtifact *expand_cache_artifact_by_hash(IdmRuntime *rt, const unsigned char hash[32]);
const IdmArtifact *expand_cache_artifact_by_key(IdmRuntime *rt, const char *env_key);
bool record_runtime_init(ExpandContext *ctx, const IdmArtifact *art, IdmSpan span, IdmError *err);
IdmArtifact *expand_cache_intern_artifact(IdmRuntime *rt, IdmArtifact *moved);
typedef enum { BODY_REC_BIND, BODY_REC_BIND_PATTERN, BODY_REC_EXPR, BODY_REC_GROUPS } BodyRecKind;
typedef struct {
    IdmArity arity;
} CallableBindingInfo;
typedef IdmCore *(*ExpandMultiClauseBodyFn)(ExpandContext *ctx, IdmCore *multi, const void *user, uint32_t argc, IdmSpan span, IdmError *err);
typedef struct {
    BodyRecKind kind;
    const IdmSyntax *form;
    const IdmSyntax *bind_name;
    size_t rhs_start;
    uint32_t bind_slot;
    IdmBindingId bind_binding_id;
    IdmArity bind_arity;
    bool bind_has_contract;
    IdmCallableContract bind_contract;
    const IdmSyntax *pattern_syntax;
    IdmPattern *pattern;
    const IdmSyntax **pattern_names;
    size_t pattern_name_count;
    uint32_t *pattern_slots;
    IdmBindingId *pattern_binding_ids;
    CallableBindingInfo *pattern_bindings;
    IdmSyntax **pin_outer;
    char **pin_fresh;
    size_t pin_count;
    size_t pin_cap;
    uint32_t pattern_tmp_slot;
    DefnGroup *groups;
    size_t group_count;
    IdmCore *core;
    size_t *deps;
    size_t dep_count;
    size_t dep_cap;
    bool callable;
    bool pure;
    bool prealloc;
    size_t order_epoch;
    bool effect;
} BodyRec;

bool activate_artifact(ExpandContext *ctx, const char *activation_name, const IdmArtifact *art, IdmScopeId base, const IdmScopeSet *act_scopes, IdmSpan span, IdmError *err);
bool callable_contract_from_value_type(const IdmTypeTerm *type, IdmCallableContract *out);
bool arg_push_slot(ExpandContext *ctx, const IdmSyntax *word, uint32_t slot);
bool arg_push_slot_with_type(ExpandContext *ctx, const IdmSyntax *word, uint32_t slot, const IdmTypeTerm *type);
bool artifact_base(ExpandContext *ctx, const IdmArtifact *art, IdmScopeId *out_base, IdmError *err);
bool artifact_init_pending(ExpandContext *ctx, const IdmArtifact *art);
bool artifact_record_nested_deps(ExpandContext *ctx, const IdmArtifact *art, IdmError *err);
const IdmArtifact *artifact_get(ExpandContext *ctx, const char *path, IdmSpan span, IdmError *err);
bool install_artifact_runtime_slots(ExpandContext *ctx, const IdmArtifact *art, IdmScopeId min_id, int64_t delta, bool once, IdmSpan span, IdmError *err);
bool install_artifact_runtime_slots_mode(ExpandContext *ctx, const IdmArtifact *art, IdmScopeId min_id, int64_t delta, bool once, bool with_imports, IdmSpan span, IdmError *err);
bool bind_artifact_exported_slots(ExpandContext *ctx, const IdmArtifact *art, const IdmScopeSet *act_scopes, IdmSpan span, IdmError *err);
bool ctx_activate_protocol_closure(ExpandContext *ctx, ProtocolDef *p, IdmError *err);
void begin_clause_context(ExpandContext *ctx, SavedClauseContext *saved);
void bits_binders_truncate(ExpandContext *ctx, size_t base);
IdmPattern *pattern_from_bitstring(ExpandContext *ctx, const IdmSyntax *syn, IdmError *err);
void begin_function_context(ExpandContext *ctx, SavedFunctionContext *saved);
const CaptureBinding *capture_lookup_existing(const CaptureBinding *captures, size_t count, const IdmSyntax *word);
typedef struct {
    const char *identity;
    const IdmArtifact *art;
} ProtocolPreActivation;
bool compile_package_module(ExpandContext *parent, const IdmSyntax *pkg, const char *unit_name_hint, const unsigned char src_hash[32], const IdmPkgSlot *inherited_slots, size_t inherited_count, const ProtocolPreActivation *preacts, size_t preact_count, IdmArtifact *out, IdmError *err);
bool ctx_activate_kernel(ExpandContext *ctx, IdmError *err);
void ctx_destroy(ExpandContext *ctx);
bool ctx_init(ExpandContext *ctx, IdmRuntime *rt);
void end_clause_context(ExpandContext *ctx, SavedClauseContext *saved);
void end_function_context(ExpandContext *ctx, SavedFunctionContext *saved);
IdmCore *expand_body_items(ExpandContext *ctx, IdmSyntax *const *items, size_t index, size_t count, bool def_scope, IdmError *err);
IdmCore *expand_package_body_items(ExpandContext *ctx, IdmSyntax *const *items, size_t index, size_t count, IdmError *err);
IdmCore *expand_package_units(ExpandContext *ctx, const IdmPackageUnit *units, size_t unit_count, IdmError *err);
IdmCore *expand_error(IdmError *err, IdmSpan span, const char *fmt, ...);
IdmCore *expand_raise_message_body(ExpandContext *ctx, const char *message, IdmSpan span, IdmError *err);
bool expand_multi_add_dispatch_clause(ExpandContext *ctx, IdmCore *multi, uint32_t argc, const char *arg0_type, ExpandMultiClauseBodyFn body_fn, const void *body_user, IdmSpan span, IdmError *err);
IdmCore *expand_activate(ExpandContext *ctx, const IdmSyntax *name_syntax, IdmSpan span, IdmError *err);
IdmCore *expand_fn_parts(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, IdmError *err);
IdmCore *expand_explain_parts(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, IdmError *err);
IdmCore *expand_function_literal(ExpandContext *ctx, const char *debug_name, const IdmSyntax *head, IdmSyntax *const *items, size_t param_start, size_t end, IdmError *err);
IdmCore *expand_function_literal_with_contract(ExpandContext *ctx, const char *debug_name, const IdmSyntax *head, IdmSyntax *const *items, size_t param_start, size_t end, const IdmCallableContract *contract, IdmError *err);
IdmCore *expand_match_form(ExpandContext *ctx, const IdmSyntax *form, IdmError *err);
bool function_literal_arity(ExpandContext *ctx, const IdmSyntax *head, IdmSyntax *const *items, size_t param_start, size_t end, IdmArity *out_arity, IdmError *err);
IdmCore *expand_implement_trait_decl(ExpandContext *ctx, const IdmSyntax *form, IdmError *err);
IdmCore *build_method_dispatch_refresh_core(ExpandContext *ctx, IdmSpan span, IdmError *err);
IdmCore *build_method_dispatcher_core(ExpandContext *ctx, const char *trait, const char *method_name, IdmSpan span, IdmError *err);
IdmCore *expand_macro_use(ExpandContext *ctx, const IdmSyntax *use_syntax, const IdmSyntax *head, uint32_t payload, IdmError *err);
IdmCore *expand_macro_use_from_parts(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, uint32_t payload, IdmError *err);
bool expand_body_macro_form_to_syntax(ExpandContext *ctx, const IdmSyntax *form, IdmSyntax **out_syntax, IdmError *err);
bool expand_surface_macro_form_to_syntax(ExpandContext *ctx, const IdmSyntax *form, IdmSyntax **out_syntax, IdmError *err);
IdmCore *expand_core_form_use_from_parts(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, const PhaseSyntaxFn *fn, IdmError *err);
IdmCore *expand_method_decl(ExpandContext *ctx, const IdmSyntax *form, IdmError *err);
IdmCore *expand_parts(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, IdmError *err);
IdmCore *expand_primitive_clause_call(IdmPrimitive primitive, IdmSpan span, IdmError *err);
bool core_call_add_arg_or_free(IdmCore *call, IdmCore *arg, IdmError *err, IdmSpan span);
IdmCore *expand_protocol_decl(ExpandContext *ctx, const IdmSyntax *form, IdmError *err);
IdmCore *expand_trait_decl(ExpandContext *ctx, const IdmSyntax *form, IdmError *err);
IdmCore *expand_template_quasiquote(ExpandContext *ctx, const IdmSyntax *t, IdmError *err);
IdmCore *expand_template_quasisyntax(ExpandContext *ctx, const IdmSyntax *t, const IdmSyntax *template_ctx, IdmError *err);
IdmCore *expand_string_literal(ExpandContext *ctx, const char *text, IdmSpan span, IdmError *err);
IdmCore *expand_receive_parts(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, IdmError *err);
IdmCore *expand_record_decl(ExpandContext *ctx, const IdmSyntax *form, IdmError *err);
IdmCore *expand_type_decl(ExpandContext *ctx, const IdmSyntax *form, IdmError *err);
IdmCore *expand_syntax(ExpandContext *ctx, const IdmSyntax *syn, IdmError *err);
IdmCore *expand_use(ExpandContext *ctx, const char *path, const char *qualifier, UseSelection *selection, const IdmSyntax *form, IdmSpan span, IdmError *err);
bool free_identifier_eq_callback(void *user, IdmRuntime *rt, const IdmSyntax *a, const IdmSyntax *b, bool *out_equal, IdmError *err);
bool identifier_bound_callback(void *user, IdmRuntime *rt, const IdmSyntax *word, bool *out_bound, IdmError *err);
bool env_push_def_binder(ExpandContext *ctx, const char *name, const IdmSyntax *name_syntax, uint32_t *out_id);
bool env_push_def_binder_with_arity(ExpandContext *ctx, const char *name, const IdmSyntax *name_syntax, IdmArity arity, const IdmCallableContract *contract, uint32_t *out_id);
bool package_slot_ref_add(ExpandContext *ctx, const char *env_key, uint32_t slot, uint32_t *out_id);
const PackageSlotRef *package_slot_ref_get(const ExpandContext *ctx, uint32_t id);
bool install_imported_macro(ExpandContext *ctx, const char *name, const IdmScopeSet *scopes, IdmModuleRef *module, uint32_t function_index, IdmPhaseEnv *phase_env, const char *provider, const char *provider_key, IdmError *err);
bool install_imported_core_form(ExpandContext *ctx, const char *name, const IdmScopeSet *scopes, IdmModuleRef *module, uint32_t function_index, IdmPhaseEnv *phase_env, const char *provider, const char *provider_key, IdmError *err);
bool install_imported_grammar(ExpandContext *ctx, const IdmPkgGrammar *grammar, const IdmScopeSet *scopes, const char *name, const char *provider, const char *provider_key, IdmScopeId min_id, int64_t delta, IdmError *err);
bool install_artifact_grammars(ExpandContext *ctx, const IdmPkgGrammar *grammars, size_t grammar_count, const IdmScopeSet *scopes, IdmScopeId min_id, int64_t delta, const char *provider, const char *provider_key, IdmError *err);
bool ctx_reader_artifact_from_active_grammars(ExpandContext *ctx, const char *surface, IdmReaderArtifact **out, IdmError *err);
bool install_imported_operator(ExpandContext *ctx, const IdmOperatorDef *op, const IdmScopeSet *binding_scopes, const char *provider, const char *provider_key, IdmError *err);
const MethodSurfaceDef *method_surface_by_index(const ExpandContext *ctx, uint32_t index);
const char *method_surface_trait_text(const MethodSurfaceDef *surface);
const char *method_surface_trait_key_text(const MethodSurfaceDef *surface);
const char *method_surface_name_text(const MethodSurfaceDef *surface);
bool method_surface_matches_trait(const ExpandContext *ctx, const MethodSurfaceDef *surface, const char *trait);
bool method_surface_matches_name(const ExpandContext *ctx, const MethodSurfaceDef *surface, const char *name);
bool method_surface_matches_identity(const ExpandContext *ctx, const MethodSurfaceDef *surface, const char *trait, const char *name);
bool method_surface_index_by_identity(const ExpandContext *ctx, const char *trait, const char *name, uint32_t *out);
bool method_surfaces_share_trait_identity(const MethodSurfaceDef *a, const MethodSurfaceDef *b);
const char *method_impl_trait_text(const MethodImplDef *impl);
const char *method_impl_name_text(const MethodImplDef *impl);
const char *method_impl_type_text(const MethodImplDef *impl);
bool method_impl_set_identity(ExpandContext *ctx, MethodImplDef *impl, const char *trait, const char *name, const char *type, IdmError *err, IdmSpan span);
bool method_impl_set_type(ExpandContext *ctx, MethodImplDef *impl, const char *type, IdmError *err, IdmSpan span);
bool method_impl_matches_type(const ExpandContext *ctx, const MethodImplDef *impl, const char *type);
char *structural_head_join(const char *head, IdmSyntax *const *items, size_t count, size_t *inout_pos);
bool structural_head_parse(const char *head, const char **out_field, size_t *out_field_len, const char **out_type);
bool type_satisfies_structural_head(const ExpandContext *ctx, const char *head, const char *type_name);
FieldSelectorDef *field_selector_lookup(ExpandContext *ctx, const char *name);
FieldSelectorDef *field_selector_ensure(ExpandContext *ctx, const char *name, IdmError *err);
IdmCore *build_field_selector_core(ExpandContext *ctx, const char *name, IdmSpan span, IdmError *err);
bool method_impl_matches_trait(const ExpandContext *ctx, const MethodImplDef *impl, const char *trait);
bool method_impl_same_type(const MethodImplDef *a, const MethodImplDef *b);
bool method_impl_matches_identity(const ExpandContext *ctx, const MethodImplDef *impl, const char *trait, const char *name, const char *type);
bool install_method_surface(ExpandContext *ctx, const char *trait, const char *trait_key, const char *name, IdmArity arity, const IdmScopeSet *scopes, const char *provider, const char *provider_key, bool has_dispatch, bool dispatch_env, const char *dispatch_env_key, uint32_t dispatch_slot, IdmError *err);
bool install_field_surfaces(ExpandContext *ctx, const TypeDef *type, uint32_t type_index, const IdmScopeSet *scopes, IdmError *err);
ProtocolDef *typed_registry_add_protocol(ExpandContext *ctx, uint32_t *out_index, IdmError *err, IdmSpan span);
TraitDef *typed_registry_add_trait(ExpandContext *ctx, uint32_t *out_index, IdmError *err, IdmSpan span);
TypeDef *typed_registry_add_type(ExpandContext *ctx, uint32_t *out_index, IdmError *err, IdmSpan span);
ProtocolDef *typed_protocol_by_index(ExpandContext *ctx, uint32_t index);
TraitDef *typed_trait_by_index(ExpandContext *ctx, uint32_t index);
TypeDef *typed_type_by_index(ExpandContext *ctx, uint32_t index);
const char *protocol_def_identity_text(const ProtocolDef *protocol);
bool protocol_def_set_identity(ExpandContext *ctx, ProtocolDef *protocol, const char *identity, IdmError *err, IdmSpan span);
bool typed_trait_matches_identity(const ExpandContext *ctx, const TraitDef *trait, const char *identity);
const TraitDef *typed_trait_by_identity(ExpandContext *ctx, const char *identity);
bool typed_type_same_identity(const TypeDef *a, const TypeDef *b);
const char *trait_def_identity_text(const TraitDef *trait);
bool trait_def_set_identity(ExpandContext *ctx, TraitDef *trait, const char *identity, IdmError *err, IdmSpan span);
const char *trait_method_name_text(const TraitMethodDef *method);
bool type_var_is_wildcard(const IdmTypeTerm *term);
bool type_var_same(const IdmTypeTerm *a, const IdmTypeTerm *b);
bool type_name_same(const ExpandContext *ctx, const char *a, const char *b);
const TraitDef *trait_by_constraint_name(ExpandContext *ctx, const char *trait);
const char *typeclass_display_name(ExpandContext *ctx, const char *trait);
bool typeclass_same_trait(ExpandContext *ctx, const char *a, const char *b);
bool typeclass_given_matches(ExpandContext *ctx, const IdmConstraint *given, const char *trait, const IdmTypeTerm *lhs);
bool trait_impl_satisfies_type(const ExpandContext *ctx, const TraitDef *trait, const char *type);
bool trait_impl_satisfies_term(const ExpandContext *ctx, const TraitDef *trait, const IdmTypeTerm *lhs);
bool trait_method_set_name(ExpandContext *ctx, TraitMethodDef *method, const char *name, IdmError *err, IdmSpan span);
bool trait_method_matches_name(const ExpandContext *ctx, const TraitMethodDef *method, const char *name);
void trait_method_def_destroy(TraitMethodDef *method);
bool trait_method_defs_copy(const TraitMethodDef *src, size_t count, TraitMethodDef **out);
bool trait_method_defs_import(ExpandContext *ctx, const IdmTraitMethodDef *src, size_t count, TraitMethodDef **out, IdmError *err, IdmSpan span);
bool trait_method_defs_export(const TraitMethodDef *src, size_t count, IdmTraitMethodDef **out);
const char *trait_method_impl_name_text(const TraitMethodImpl *impl);
bool trait_method_impl_set_name(ExpandContext *ctx, TraitMethodImpl *impl, const char *name, IdmError *err, IdmSpan span);
bool trait_method_impl_matches_name(const ExpandContext *ctx, const TraitMethodImpl *impl, const char *name);
const char *type_def_identity_text(const TypeDef *type);
const TypeDef *type_def_lookup_name(const ExpandContext *ctx, const char *name);
const TypeDef *typed_type_by_identity(const ExpandContext *ctx, const char *identity);
IdmSymbol *type_def_identity_symbol(const TypeDef *type);
bool type_def_set_identity(ExpandContext *ctx, TypeDef *type, const char *identity, IdmError *err, IdmSpan span);
const char *type_field_name_text(const TypeFieldDef *field);
const IdmTypeTerm *type_field_contract_term(const TypeFieldDef *field);
bool type_field_set(ExpandContext *ctx, TypeFieldDef *field, const char *name, const IdmTypeTerm *contract, IdmError *err, IdmSpan span);
bool type_field_matches_name(const ExpandContext *ctx, const TypeFieldDef *field, const char *name);
bool parse_type_term_parts(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, IdmTypeTerm *out, IdmError *err);
bool parse_callable_contract_parts(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, IdmCallableContract *out, IdmError *err);
bool expand_typecheck_value(ExpandContext *ctx, const char *name, IdmCore **value, IdmCallableContract *contract, bool *has_contract, bool declared, IdmError *err);
bool expand_typecheck_statement(ExpandContext *ctx, IdmCore **core, IdmError *err);
bool expand_solved_type_set(ExpandContext *ctx, const IdmCore *core, IdmTypeTerm *term);
const IdmTypeTerm *expand_solved_type_lookup(const ExpandContext *ctx, const IdmCore *core);
void expand_solved_types_clear(ExpandContext *ctx);
typedef struct {
    const char **items;
    size_t count;
    size_t cap;
} TypeNameList;
bool is_a_target_names(ExpandContext *ctx, const char *name, TypeNameList *out, IdmError *err);
bool expand_lower_root(ExpandContext *ctx, IdmCore **root, IdmError *err);
bool expand_core_is_primitive_call(const IdmCore *core, IdmPrimitive primitive);
IdmCore *decl_done(IdmError *err);
int expand_dispatch_select_impl(ExpandContext *ctx, const IdmCore *node, const char *receiver_type, uint32_t argc, size_t *out);
bool expand_dispatch_route_method(ExpandContext *ctx, IdmCore *node, const char *receiver_type, IdmError *err);
bool expand_dispatch_route_field(ExpandContext *ctx, IdmCore *node, const char *receiver_type, IdmError *err);
bool expand_typecheck_infer_scheme(ExpandContext *ctx, const IdmCore *value, const char *name, IdmCallableContract *out, bool *out_has, IdmError *err);
bool expand_typecheck_defn_groups(ExpandContext *ctx, const DefnGroup *groups, IdmCore **values, size_t count, IdmError *err);
typedef struct {
    uint8_t level;
    IdmArgMask invoked;
} PurityFx;
bool expand_typecheck_purity(ExpandContext *ctx, const DefnGroup *groups, IdmCore **values, size_t count, PurityFx *out_fx, IdmError *err);
bool expand_typecheck_core_purity(ExpandContext *ctx, const IdmCore *core, uint8_t *out_level, IdmArgMask *out_invoked, IdmError *err);
IdmEnv *expand_unit_runtime_env(ExpandContext *ctx);
void expand_seed_const_defn(ExpandContext *ctx, uint32_t slot, IdmCore *value);
IdmCore *expand_record_field_core(ExpandContext *ctx, IdmCore *receiver, const TypeDef *type, uint32_t field_index, IdmSpan span, IdmError *err);
bool invoke_macro_to_syntax(ExpandContext *ctx, const IdmSyntax *use_syntax, const IdmSyntax *head, uint32_t payload, IdmSyntax **out_syntax, IdmError *err);
IdmCore *literal_from_syntax(ExpandContext *ctx, const IdmSyntax *syn, IdmError *err);
bool local_expand_callback(void *user, IdmRuntime *rt, const IdmSyntax *syntax, IdmSyntax **out_syntax, IdmError *err);
bool dict_rest_index(const IdmSyntax *syn, size_t *out_index, IdmError *err);
bool try_qualified_word_at(IdmSyntax *const *items, size_t start, size_t end, IdmSyntax **out_word, size_t *out_end, IdmError *err);
IdmSyntax *expect_qualified_word_at(IdmSyntax *const *items, size_t start, size_t *inout_end, const char *message, IdmError *err);
bool expand_arity_auto_calls_zero(const IdmArity *arity);
bool expand_syntax_call_arity(ExpandContext *ctx, const IdmSyntax *syn, IdmArity *out, IdmError *err);
bool local_macro_invoke(void *user, IdmRuntime *rt, uint32_t payload, const IdmSyntax *use_syntax, IdmSyntax **out_syntax, IdmError *err);
void local_pop_to(ExpandContext *ctx, size_t table_base, uint32_t next_slot);
bool local_push_def_binder(ExpandContext *ctx, const char *name, const IdmSyntax *name_syntax, uint32_t *out_slot);
bool local_push_def_binder_with_arity(ExpandContext *ctx, const char *name, const IdmSyntax *name_syntax, IdmArity arity, const IdmCallableContract *contract, uint32_t *out_slot);
bool local_push_scoped(ExpandContext *ctx, const char *name, const IdmSyntax *name_syntax, uint32_t *out_slot);
void grammar_def_destroy(GrammarDef *grammar);
void macro_def_destroy(MacroDef *macro);
void phase_syntax_fn_destroy(PhaseSyntaxFn *fn);
bool materialize_capture(ExpandContext *ctx, const IdmSyntax *word, const IdmBinding *b, uint32_t *out);
bool materialize_slot_capture(ExpandContext *ctx, const char *name, const IdmScopeSet *scopes, uint32_t frame_id, uint32_t slot, IdmArity arity, uint32_t *out);
const IdmOperatorDef *op_lookup(const ExpandContext *ctx, const IdmSyntax *syn, bool want_prefix);
const IdmOperatorDef *op_lookup_syntax_capture(const ExpandContext *ctx, const IdmSyntax *syn, bool want_left, IdmError *err);
bool operator_capture_compile(const char *capture, uint8_t *out_kind, bool *out_left, uint32_t *out_count);
bool artifact_bind_name(const char *qualifier, const char *name, const char **out_name, char **owned, IdmError *err, IdmSpan span);
const char *package_path_text(const IdmSyntax *syn);
const char *surface_token_text(const IdmSyntax *syn);
char *surface_token_text_dup(const IdmSyntax *syn);
char *scoped_identity(ExpandContext *ctx, const char *name, const IdmSyntax *form, unsigned char out_hash[32], IdmError *err);
bool predeclare_trait_methods(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t count, IdmError *err);
void protocol_def_destroy(ProtocolDef *protocol);
void trait_def_destroy(TraitDef *trait);
void type_def_destroy(TypeDef *type);
bool record_package_slot(ExpandContext *ctx, const char *name, uint32_t slot_id, const IdmScopeSet *scopes, IdmArity arity, const IdmCallableContract *contract, bool exported);
bool fn_primitive_passthrough(const IdmCore *fn, uint32_t *out_primitive);
bool register_macro(ExpandContext *ctx, const IdmSyntax *name_syntax, IdmCore *fn, IdmSpan span, bool exported, IdmError *err);
bool register_operator(ExpandContext *ctx, const char *name, const char *capture, uint8_t precedence, IdmOpAssoc assoc, uint8_t action, const char *target_name, const IdmScopeSet *scopes, const IdmScopeSet *binding_scopes, const char *provider, const char *provider_key, bool exported, IdmSpan span, IdmError *err);
bool register_core_form(ExpandContext *ctx, const IdmSyntax *name_syntax, IdmCore *fn, IdmSpan span, IdmError *err);
bool register_reader_form(ExpandContext *ctx, const char *name, const IdmScopeSet *scopes, const IdmEnforestNode *node, IdmError *err);
bool register_reader_form_transformer(ExpandContext *ctx, const char *name, const IdmScopeSet *scopes, IdmCore *fn, IdmSpan span, IdmError *err);
bool register_reader_form_fn(ExpandContext *ctx, const char *name, const IdmScopeSet *scopes, const PhaseSyntaxFn *fn, IdmError *err);
bool bind_reader_form(ExpandContext *ctx, const char *name, const IdmScopeSet *scopes, const IdmEnforestNode *node, const PhaseSyntaxFn *fn, IdmError *err);
bool phase_candidate_stage(ExpandContext *ctx, const char *name, const IdmSyntax *name_syntax, IdmSyntax *const *items, size_t count, size_t run_id, IdmError *err);
size_t phase_candidate_next_run(ExpandContext *ctx);
bool phase_demand_local(ExpandContext *ctx, const IdmSyntax *word, bool *out_compiled, IdmError *err);
const IdmReaderArtifact *ctx_active_reader(ExpandContext *ctx, IdmError *err);
void ctx_reader_invalidate(ExpandContext *ctx);
bool expand_unit_read(ExpandContext *ctx, const char *label, const char *source, size_t offset, IdmSyntax **out, IdmError *err);
bool expand_unit_open_at(const ExpandContext *ctx, IdmSpan span);
bool install_imported_reader_form(ExpandContext *ctx, const IdmPkgReaderForm *form, const IdmScopeSet *scopes, IdmModuleRef *module, IdmPhaseEnv *fallback_phase_env, IdmError *err);
IdmEnforestNode *idm_enforest_parse(const IdmSyntax *term, IdmError *err);
IdmCore *expand_reader_form_transform(ExpandContext *ctx, const IdmSyntax *syn, const PhaseSyntaxFn *fn, IdmError *err);
void reader_form_binding_free(void *data);
bool register_grammar(ExpandContext *ctx, const IdmSyntax *name_syntax, uint8_t mode, IdmGrammarRule *rules, size_t rule_count, IdmGrammarPair *pairs, size_t pair_count, bool exported, IdmError *err);
IdmBytecodeModule *relocated_module_copy(ExpandContext *ctx, const IdmBytecodeModule *src, IdmScopeId min_id, int64_t delta, uint32_t *out_fn_off, IdmError *err);
const IdmBinding *resolve_default(const ExpandContext *ctx, const IdmSyntax *word, IdmResolveStatus *out_status);
IdmResolveStatus resolve_scoped(const ExpandContext *ctx, const char *name, IdmBindingSpace space, const IdmScopeSet *base, const IdmScopeSet *fallback, const IdmBinding **out_binding);
bool resolve_head_core_form(ExpandContext *ctx, const IdmSyntax *head, const PhaseSyntaxFn **out_fn, IdmError *err);
bool resolve_head_core_form_exact(ExpandContext *ctx, const IdmSyntax *head, const PhaseSyntaxFn **out_fn, IdmError *err);
ProtocolDef *resolve_protocol_def(ExpandContext *ctx, const IdmSyntax *name_syntax, IdmResolveStatus *out_status);
TraitDef *resolve_trait_def(ExpandContext *ctx, const IdmSyntax *name_syntax, IdmResolveStatus *out_status);
TypeDef *resolve_type_def(ExpandContext *ctx, const IdmSyntax *name_syntax, IdmResolveStatus *out_status);
bool resolve_transformer(ExpandContext *ctx, const IdmSyntax *head, uint32_t *out_payload, IdmError *err);
bool surface_parts_have_operator_boundary(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, IdmError *err);
bool run_phase_core(ExpandContext *ctx, IdmCore *core, IdmError *err);
void surface_checkpoint(ExpandContext *ctx, SurfaceCheckpoint *checkpoint);
void surface_rollback(ExpandContext *ctx, const SurfaceCheckpoint *checkpoint);
void surface_discard(ExpandContext *ctx, const SurfaceCheckpoint *checkpoint);
IdmSyntax *syntax_use_from_parts(ExpandContext *ctx, IdmSyntax *const *items, size_t start, size_t end, IdmError *err);
bool syn_is_word(const IdmSyntax *syn, const char *word);
bool syntax_scopes_copy(IdmScopeSet *dst, const IdmSyntax *syn);
bool value_from_literal_syntax(ExpandContext *ctx, const IdmSyntax *syn, IdmValue *out, IdmError *err);
bool expand_quote_datum(ExpandContext *ctx, const IdmSyntax *t, IdmValue *out, IdmError *err);
IdmCore *wrap_kernel_use(ExpandContext *ctx, IdmCore *body, IdmError *err);
IdmCore *wrap_artifact_runtime_init(ExpandContext *ctx, const IdmArtifact *art, IdmScopeId min_id, int64_t delta, bool borrow_module, bool allow_empty_module, IdmCore *body, IdmSpan span, IdmError *err);
IdmCore *wrap_phase_runtime_inits(ExpandContext *ctx, IdmCore *body, IdmError *err);
IdmCore *wrap_phase_runtime_inits_since(ExpandContext *ctx, IdmCore *body, size_t first_mark, IdmError *err);

bool expand_surface_value(ExpandContext *ctx, IdmRuntime *rt, const char *kind, IdmValue *out, IdmError *err);
void hooks_install(IdmRuntime *rt, ExpandContext *ctx, SavedHooks *saved);
void hooks_restore(IdmRuntime *rt, const SavedHooks *saved);
void ctx_set_unit(ExpandContext *ctx, const char *name, const unsigned char hash[32]);
bool record_activation(ExpandContext *ctx, const char *name, const char *provider, const char *provider_key, IdmSpan span, IdmError *err);
int surface_install_guard(ExpandContext *ctx, const char *provider, const char *provider_key, const char *key, const char *display, IdmBindingSpace space, const IdmScopeSet *scopes, IdmError *err);
void expand_edge_record(ExpandContext *ctx, const char *kind, const char *name, const char *provider, const char *doc, const IdmSyntax *before, const IdmSyntax *after, IdmSpan span);
void expand_edges_truncate(ExpandContext *ctx, size_t base);
bool expand_edge_value(ExpandContext *ctx, IdmRuntime *rt, const ExpandEdge *edge, IdmValue *out, IdmError *err);
int surface_bind_payload(ExpandContext *ctx, const char *provider, const char *provider_key, const char *key, const char *display, IdmBindingSpace space, IdmBindingKind kind, const IdmScopeSet *scopes, uint32_t payload, IdmSpan span, IdmError *err);
int surface_bind_data(ExpandContext *ctx, const char *provider, const char *provider_key, const char *key, const char *display, IdmBindingSpace space, IdmBindingKind kind, const IdmScopeSet *scopes, void *data, IdmSpan span, IdmError *err);
void artifact_provider_key(const unsigned char hash[32], char out[17]);
char *operator_binding_key(const char *name, const char *capture);
bool scopes_subset_for_ref(const IdmScopeSet *binding_scopes, const IdmSyntax *ref);
bool binder_scopes_pruned(ExpandContext *ctx, const IdmSyntax *name_syntax, IdmScopeSet *out);

#endif
